apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data
  namespace: numeriseur
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 200Mi
